// <auto-generated />
using System;
using Draft15.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Draft15.Migrations
{
    [DbContext(typeof(Draft15Context))]
    [Migration("20240225161213_addquizentity")]
    partial class addquizentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppData.Assignment", b =>
                {
                    b.Property<int>("assignment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("assignment_id"));

                    b.Property<string>("assignment_description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("assignment_title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("attemp")
                        .HasColumnType("integer");

                    b.Property<int>("course_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("due_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("assignment_id");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("AppData.Content", b =>
                {
                    b.Property<int>("content_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("content_id"));

                    b.Property<string>("content_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("course_id")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("date");

                    b.Property<bool>("isFinish")
                        .HasColumnType("boolean");

                    b.Property<int?>("prerequisitecontent_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("date");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("content_id");

                    b.HasIndex("prerequisitecontent_id");

                    b.ToTable("Content");
                });

            modelBuilder.Entity("AppData.File", b =>
                {
                    b.Property<int>("file_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("file_id"));

                    b.Property<int?>("assignment_id")
                        .HasColumnType("integer");

                    b.Property<int?>("content_id")
                        .HasColumnType("integer");

                    b.Property<string>("file_name")
                        .HasColumnType("text");

                    b.Property<string>("file_path")
                        .HasColumnType("text");

                    b.Property<string>("file_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("submission_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("uploadDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("file_id");

                    b.HasIndex("assignment_id");

                    b.HasIndex("content_id");

                    b.HasIndex("submission_id");

                    b.ToTable("File");
                });

            modelBuilder.Entity("AppData.Quiz", b =>
                {
                    b.Property<int>("quiz_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("quiz_id"));

                    b.Property<int>("content_id")
                        .HasColumnType("integer");

                    b.Property<int>("duration")
                        .HasColumnType("integer");

                    b.Property<string>("quiz_title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("quiz_id");

                    b.HasIndex("content_id");

                    b.ToTable("Quiz");
                });

            modelBuilder.Entity("AppData.QuizAttempt", b =>
                {
                    b.Property<int>("attempt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("attempt_id"));

                    b.Property<int>("quiz_id")
                        .HasColumnType("integer");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("attempt_id");

                    b.HasIndex("quiz_id");

                    b.ToTable("QuizAttempt");
                });

            modelBuilder.Entity("AppData.QuizOption", b =>
                {
                    b.Property<int>("option_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("option_id"));

                    b.Property<bool>("isCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("option_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("quesion_id")
                        .HasColumnType("integer");

                    b.Property<int?>("question_id")
                        .HasColumnType("integer");

                    b.HasKey("option_id");

                    b.HasIndex("question_id");

                    b.ToTable("QuizOption");
                });

            modelBuilder.Entity("AppData.QuizQuestion", b =>
                {
                    b.Property<int>("question_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("question_id"));

                    b.Property<string>("quesion_content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("quesion_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("quiz_id")
                        .HasColumnType("integer");

                    b.HasKey("question_id");

                    b.HasIndex("quiz_id");

                    b.ToTable("QuizQuestion");
                });

            modelBuilder.Entity("AppData.QuizResponse", b =>
                {
                    b.Property<int>("response_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("response_id"));

                    b.Property<int>("attempt_id")
                        .HasColumnType("integer");

                    b.Property<int>("choosenoption_id")
                        .HasColumnType("integer");

                    b.Property<int>("question_id")
                        .HasColumnType("integer");

                    b.HasKey("response_id");

                    b.HasIndex("attempt_id");

                    b.HasIndex("choosenoption_id");

                    b.HasIndex("question_id");

                    b.ToTable("QuizResponse");
                });

            modelBuilder.Entity("AppData.Submission", b =>
                {
                    b.Property<int>("submission_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("submission_id"));

                    b.Property<int>("assignment_id")
                        .HasColumnType("integer");

                    b.Property<string>("comment")
                        .HasColumnType("text");

                    b.Property<int?>("grade")
                        .HasColumnType("integer");

                    b.Property<DateTime>("submission_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("submission_id");

                    b.HasIndex("assignment_id");

                    b.ToTable("Submission");
                });

            modelBuilder.Entity("AppData.UserContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("content_id")
                        .HasColumnType("integer");

                    b.Property<bool>("isFinish")
                        .HasColumnType("boolean");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("content_id");

                    b.ToTable("UserContent");
                });

            modelBuilder.Entity("AppData.Content", b =>
                {
                    b.HasOne("AppData.Content", "prerequisite")
                        .WithMany()
                        .HasForeignKey("prerequisitecontent_id");

                    b.Navigation("prerequisite");
                });

            modelBuilder.Entity("AppData.File", b =>
                {
                    b.HasOne("AppData.Assignment", null)
                        .WithMany("files")
                        .HasForeignKey("assignment_id");

                    b.HasOne("AppData.Content", null)
                        .WithMany("files")
                        .HasForeignKey("content_id");

                    b.HasOne("AppData.Submission", null)
                        .WithMany("files")
                        .HasForeignKey("submission_id");
                });

            modelBuilder.Entity("AppData.Quiz", b =>
                {
                    b.HasOne("AppData.Content", "Content")
                        .WithMany()
                        .HasForeignKey("content_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("AppData.QuizAttempt", b =>
                {
                    b.HasOne("AppData.Quiz", "Quiz")
                        .WithMany("attempts")
                        .HasForeignKey("quiz_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("AppData.QuizOption", b =>
                {
                    b.HasOne("AppData.QuizQuestion", "question")
                        .WithMany("options")
                        .HasForeignKey("question_id");

                    b.Navigation("question");
                });

            modelBuilder.Entity("AppData.QuizQuestion", b =>
                {
                    b.HasOne("AppData.Quiz", "Quiz")
                        .WithMany("questions")
                        .HasForeignKey("quiz_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("AppData.QuizResponse", b =>
                {
                    b.HasOne("AppData.QuizAttempt", "attempt")
                        .WithMany("responses")
                        .HasForeignKey("attempt_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.QuizOption", "choosen")
                        .WithMany()
                        .HasForeignKey("choosenoption_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.QuizQuestion", "question")
                        .WithMany()
                        .HasForeignKey("question_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("attempt");

                    b.Navigation("choosen");

                    b.Navigation("question");
                });

            modelBuilder.Entity("AppData.Submission", b =>
                {
                    b.HasOne("AppData.Assignment", "assignment")
                        .WithMany("submissions")
                        .HasForeignKey("assignment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assignment");
                });

            modelBuilder.Entity("AppData.UserContent", b =>
                {
                    b.HasOne("AppData.Content", "Content")
                        .WithMany("UserContents")
                        .HasForeignKey("content_id");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("AppData.Assignment", b =>
                {
                    b.Navigation("files");

                    b.Navigation("submissions");
                });

            modelBuilder.Entity("AppData.Content", b =>
                {
                    b.Navigation("UserContents");

                    b.Navigation("files");
                });

            modelBuilder.Entity("AppData.Quiz", b =>
                {
                    b.Navigation("attempts");

                    b.Navigation("questions");
                });

            modelBuilder.Entity("AppData.QuizAttempt", b =>
                {
                    b.Navigation("responses");
                });

            modelBuilder.Entity("AppData.QuizQuestion", b =>
                {
                    b.Navigation("options");
                });

            modelBuilder.Entity("AppData.Submission", b =>
                {
                    b.Navigation("files");
                });
#pragma warning restore 612, 618
        }
    }
}
